<?php require 'templates/header.phtml' ?>

<div>
    <h1>Nosotros</h1>
    <p>En una tranquila ciudad, dos amigos apasionados por la tecnología, Lautaro y Joaquín, decidieron emprender un emocionante viaje juntos. Compartían una visión de negocios sólida y una profunda pasión por los ordenadores. Con el tiempo, dieron vida a su empresa y la llamaron "LJ", en honor a sus propios nombres.

        Lautaro y Joaquín se conocían desde hace años, habían compartido su amor por la tecnología desde la infancia. Después de muchas conversaciones y planificación, finalmente decidieron dar el salto y convertir su sueño en realidad. Lautaro era un experto en hardware, mientras que Joaquín destacaba en software y estrategias de marketing. Juntos, se complementaban de manera perfecta.

        El comienzo de su aventura empresarial tuvo lugar en el garaje de la casa de Lautaro. Con un presupuesto limitado pero un entusiasmo ilimitado, comenzaron a vender piezas de hardware, desde tarjetas gráficas hasta discos duros. Además, crearon su sitio web y se aventuraron en las redes sociales para dar a conocer su negocio.

        Los primeros meses fueron un desafío. Se enfrentaron a obstáculos financieros y a una competencia feroz, pero su pasión por la tecnología y su compromiso con la satisfacción del cliente los mantuvieron enfocados. No solo vendían productos, sino que ofrecían asesoramiento y recomendaciones personalizadas, lo que los diferenciaba de otros competidores.

        Con el tiempo, "LJ" comenzó a crecer. Su reputación se expandía y con ella su clientela. Ofrecían productos de alta calidad y un servicio excepcional, lo que generó una base de clientes leales. No solo vendían componentes de hardware, sino que también ofrecían servicios de reparación y mantenimiento de computadoras. Como resultado, abrieron su primera tienda física, lo que marcó un hito importante en su viaje empresarial.

        A medida que "LJ" prosperaba, Lautaro y Joaquín continuaron siendo amigos cercanos y socios leales. Su empresa no era solo un negocio, sino una manifestación de su pasión compartida por la tecnología y su compromiso con la satisfacción del cliente. La historia de Lautaro y Joaquín, y su empresa "LJ", es un ejemplo inspirador de cómo la amistad y la pasión pueden llevar al éxito empresarial.</p>
</div>

<?php require 'templates/footer.phtml' ?>