<!-- Contenido principal de tu página -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</main>
<footer>
<div class="redes-sociales">
    <a href="https://www.facebook.com/" target="_blank"><img src="facebook.png" alt="Facebook"></a>
    <a href="https://www.instagram.com/" target="_blank"><img src="instagram.png" alt="Instagram"></a>
</div>
        <p>© 2023 LJ</p>
    </footer>