<form action="agregar-marca" method="post">
    <div class="form-group">
        <label for="marca">Marca:</label>
        <input type="text" id="marca" name="marca" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="sede">Sede:</label>
        <input type="text" id="sede" name="sede" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="descripcion">Descripción de la Marca:</label>
        <textarea id="descripcion" name="descripcion" rows="4" class="form-control" required></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Agregar Marca</button>
</form>