<!DOCTYPE html>
<html lang="es">

<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">
    <title>Tienda de Artículos de Computación</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a href="product">Productos</a></li>
                <li><a href="datosMarcas">DatosMarcas</a></li>
                <li><a href="datosProductos">DatosProductos</a></li>
                <li><a href="logout">Cerrar Sesion</a></li>
            
            </ul>
        </nav>
    </header>

    <main>