<!DOCTYPE html>
<html lang="en">

<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">

    <title>Tienda de Artículos de Computación</title>
</head>

<body>
    <header>
        <nav>
            <ul>

                <li><a href="product">Productos</a></li>
                <li><a href="about">Nosotros</a></li>
                <?php if (isset($_SESSION['USER_ID'])) : ?>
                    <li><a href="logout">Cerrar Sesión</a></li>
                <?php else : ?>
                    <li><a href="login">Iniciar Sesión</a></li>
                <?php endif ?>

            </ul>

        </nav>

    </header>

    <main>