<?php require 'templates/header.phtml' ?>


<?php foreach ($types as $type) : ?>
    <a href="product/<?= $marca_filter ?>/<?= $type->tipo_de_product ?>" class="filter-link active"><?= $type->tipo_de_product ?></a>


<?php endforeach; ?>
<a href="product/<?= $marca_filter ?>" class="filter-link">Borrar Filtros</a>
<a href="product" class="filter-link">Volver</a>


<?php foreach ($products_sinParams as $product) : ?>

    <a href="product/<?= $marca_filter ?>/<?= $product->tipo_de_product ?>/<?= $product->product_id ?>">
        <ul>
            <li class="liProducts"><?= $product->nombre_producto; ?></li>
        </ul>
    </a>


<?php endforeach; ?>



<?php require 'templates/footer.phtml' ?>