<?php require 'templates/header.phtml' ?>
<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="register-auth">
        <div class="form-group">
            <label for="user">Usuario</label>
            <input  class="form-control" id="user" name="user" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password"  class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Registrarse</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>